### PR TITLE
Responsive design + User interactivity 

### PR DESCRIPTION
**Pull request by Waishnav**
Hi Chinmay, I've added lots of things in terms of design. The updated design is more engaging, which might help you draw players into your game. Just have a look at the following screenshots and Do let me know if any changes need to be made...

Previous UI          |  New UI
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by JawHawk** [comment]
@Waishnav The design is great, but it gets distorted for screen sizes < 500px, which needs to be fixed

**Comment by JawHawk** [comment]
> Hi Chinmay, I've added lots of things in terms of design. The updated design is more engaging, which might help you draw players into your game. Just have a look at the following screenshots and Do let me know if any changes need to be made...
> 
> Previous UI	New UI
> 	

@Waishnav The design is great, but it gets distorted for screen sizes < 500px, which needs to be fixed

**Comment by Waishnav** [comment]
Alright, I've got the issue. I will solve this issue as soon as possible.

**Comment by Waishnav** [comment]
Hey issue is solved you can check [here](https://magical-kashata-5e2ffb.netlify.app)
Also, I've two suggestions,
1. For the mobile screen user, it is difficult to figure out the first-move user, as I've made `display: none` to "turn of: circle" div for the mobile screen. So to solve this issue you can add PopUp to notify players about the first mover.
2. To add more interactivity, you can make the opacity 0.5 to the button which has zero frequency left.

I can work on 2nd suggestion, but I need help from you to understand the code.

**Pull request merged**
